services:
  - type: web
    name: galaxy-trail-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
      - key: USE_WEBHOOK
      - key: WEBHOOK_URL
      - key: WEBHOOK_PATH
      - key: NASA_API_KEY
      - key: OPENWEATHER_KEY
      - key: NEWS_API_KEY
